# -*- coding: utf-8 -*-
"""battle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qk8uvCv6HfXzYDlP1ksftfx9t6VrbA2V
"""

import random
import time

player_hp = 10
enemy_hp = 10

def player_attack(enemy_hp):
    damage = random.randint(1, 10)
    print("プレイヤーの攻撃！")
    time.sleep(1)
    enemy_hp -= damage
    print(f"{damage}のダメージ！")
    return enemy_hp

def player_heal(player_hp):
    heal = random.randint(1, 5)
    print("プレイヤーは回復！")
    time.sleep(1)
    player_hp += heal
    print(f"{heal}回復した！")
    return player_hp

def enemy_attack(player_hp):
    damage = random.randint(1, 10)
    print("CPUの攻撃！")
    time.sleep(1)
    player_hp -= damage
    print(f"{damage}のダメージ！")
    return player_hp

def enemy_heal(enemy_hp):
    heal = random.randint(1, 5)
    print("CPUは回復！")
    time.sleep(1)
    enemy_hp += heal
    print(f"{heal}回復した！")
    return enemy_hp

while enemy_hp > 0 and player_hp > 0:
    print(f"\nHP: プレイヤー{player_hp} / CPU{enemy_hp}")
    print("プレイヤーのターン！")

    battle_option = int(input("1:攻撃 2:回復 > "))

    if battle_option == 1:
        enemy_hp = player_attack(enemy_hp)
    elif battle_option == 2:
        player_hp = player_heal(player_hp)
    else:
        print("1か2を選択してください")
        continue

    if enemy_hp <= 0:
        break

    print("CPUのターン...")
    cpu_option = random.randint(1, 2)

    if cpu_option == 1:
        player_hp = enemy_attack(player_hp)
    else:
        enemy_hp = enemy_heal(enemy_hp)


print("\n------")
if player_hp <= 0:
    print("CPUの勝利")
else:
    print("プレイヤーの勝利")